describe('Level 8 Programme', () => {
    it('Apply to Level 8 Programme', () => {
      cy.visit('https://learningneverends.iob.ie')
      cy.viewport(1334, 740)
      cy.get('.meganav-menu:nth-child(1) > .arrow-head').click()
      cy.get('.learn-meganav-columns:nth-child(4) li:nth-child(3) p').click()
      cy.get('.scroller__arrows--right').click()
      cy.get('.swiper-slide:nth-child(4) .programmes-card__top__header').click()
      cy.contains('Apply now').click()
      cy.get('input:nth-child(3)').click().type('D9534')
      cy.get('#password').click().type('Pass1234')
      cy.get('#next').click()
      cy.get('.radio:nth-child(2) > .collection_radio_buttons').click()
      cy.get('#applications_p1_programme_0').select('Banking Operations and Digital')
      cy.get('.applications_p1_file_0 .input-selector').click().type('C:\\fakepath\\Untitled.rtf')
      cy.get('.boolean:nth-child(3)').click()
      cy.get('input[name="commit"]').click()
      cy.get('a:contains("Go to homepage")').click()
      cy.get('.meganav-menu:nth-child(1) > .arrow-head').click()
      cy.get('.learn-meganav-columns:nth-child(4) li:nth-child(3) p').click()
      cy.get('.swiper-slide-active .programmes-card__top').click()
      cy.get('.swiper-slide-next .programmes-card__top__header').click()
    })
  })
  
